name: Demo Workflow
on: 
  pull_request

jobs: 
  Markdown-Linter:
    runs-on: ubuntu-latest
    steps:
    - name: markdownlint-cli
      uses: avto-dev/markdown-lint@v1
      with:
        args: '.'
        config: '.markdownlint.yml'