name: Build and zip Jekyll and publish it to GitHub packages

on:
  push:
    tags:
      - '*'

jobs:
  publish-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Ckechout git repo
        uses: actions/checkout@v4
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Create .zip File
        uses: TheDoctor0/zip-release@0.7.1
        with:
          path: './_site/*'
      - name: Upload Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}